// Generated by scripts/split-agent-eyes.py: run it again after changing an icon in
// public/images/agents/. Each 3D icon is split into its body and its eyes
// (public/images/agents/parts/), so AgentMascot.vue can move the eyes on their own.
// Values are percentages of the icon.

export interface MascotGeometry {
  /** Middle point between the two eyes */
  eyesX: number;
  eyesY: number;
  /** How far the eyes can glance sideways and stay on the body */
  look: number;
  /** Middle of the bottom of the body, where its shadow sits */
  baseX: number;
  baseY: number;
  /** Width of the body */
  width: number;
  /** Middle of a part floating free of the body, like Airene's sparkle (<icon>-extra.png) */
  extraX?: number;
  extraY?: number;
}

export const MASCOT_GEOMETRY: Record<string, MascotGeometry> = {
  airene: {
    eyesX: 48.9,
    eyesY: 52.4,
    look: 10,
    baseX: 47.7,
    baseY: 96.5,
    width: 92.2,
    extraX: 84.6,
    extraY: 17.2
  },
  "arch-orange": { eyesX: 52.1, eyesY: 45.2, look: 10, baseX: 49.8, baseY: 80.5, width: 96.5 },
  "ball-yellow": { eyesX: 55, eyesY: 48.9, look: 10, baseX: 50, baseY: 96.9, width: 96.9 },
  "bowtie-orange": { eyesX: 50.8, eyesY: 46, look: 10, baseX: 49.8, baseY: 84.4, width: 96.5 },
  "box-blue": { eyesX: 54.7, eyesY: 52, look: 10, baseX: 49.8, baseY: 94.9, width: 96.5 },
  "bubbles-yellow": { eyesX: 51.1, eyesY: 52.7, look: 10, baseX: 50, baseY: 77.3, width: 96.9 },
  "bunny-pink": { eyesX: 53.1, eyesY: 66.9, look: 10, baseX: 50, baseY: 98.4, width: 93 },
  "cloud-beige": { eyesX: 54.1, eyesY: 54.1, look: 10, baseX: 49.8, baseY: 81.6, width: 96.5 },
  "cloud-purple": { eyesX: 51.4, eyesY: 50.2, look: 10, baseX: 50, baseY: 79.3, width: 96.9 },
  "cloud-yellow": { eyesX: 51, eyesY: 53.2, look: 10, baseX: 50, baseY: 80.9, width: 96.9 },
  "corner-green": { eyesX: 50, eyesY: 56.1, look: 10, baseX: 50, baseY: 85.5, width: 96.9 },
  "diamond-purple": { eyesX: 50.9, eyesY: 50.3, look: 10, baseX: 50.2, baseY: 89.1, width: 96.5 },
  "drop-blue": { eyesX: 52.7, eyesY: 62.2, look: 10, baseX: 50, baseY: 98.4, width: 92.2 },
  "peaks-red": { eyesX: 52.8, eyesY: 52.1, look: 10, baseX: 50.2, baseY: 73.8, width: 96.5 },
  "peaks-teal": { eyesX: 52.1, eyesY: 52.6, look: 10, baseX: 50.2, baseY: 77, width: 96.5 },
  "pentagon-blue": { eyesX: 51.7, eyesY: 54.3, look: 10, baseX: 50, baseY: 89.8, width: 96.1 },
  "pentagon-teal": { eyesX: 52.2, eyesY: 53.3, look: 10, baseX: 50.2, baseY: 91, width: 96.5 },
  "plus-blue": { eyesX: 52.3, eyesY: 52.3, look: 10, baseX: 50.2, baseY: 88.3, width: 96.5 },
  "star-navy": { eyesX: 53.2, eyesY: 51.7, look: 10, baseX: 50.2, baseY: 90.2, width: 96.5 },
  "step-green": { eyesX: 56.4, eyesY: 57.1, look: 9.4, baseX: 50.2, baseY: 85.9, width: 96.5 }
};
